name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Create and activate conda environment
      run: |
        conda config --set always_yes yes
        conda info -a
        conda env create --file /home/runner/work/PyUPPAAL-Automation/PyUPPAAL-Automation/environment.yml --name myenv
        conda init bash
        source ~/.bashrc
        conda activate myenv
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Install ChromeDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/125.0.6422.141/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
    #   run: |
    #     source ~/.bashrc
    #     conda activate myenv
    #     conda install flake8
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Get Verifyta
      run: |
        source ~/.bashrc
        conda activate myenv
        pip install selenium
        python /home/runner/work/PyUPPAAL-Automation/PyUPPAAL-Automation/.github/workflows/get_uppaal.py
    - name: Install pyuppaal
      run: |
        source ~/.bashrc
        conda activate myenv
        pip install -e /home/runner/work/PyUPPAAL-Automation/PyUPPAAL-Automation/
    - name: Test with pytest
      run: |
        source ~/.bashrc
        conda activate myenv
        conda install pytest
        pytest
